<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container61VjPdR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container61VjPdR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container61VjPdR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container61VjPdR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container61VjPdR\App_KernelDevDebugContainer([
    'container.build_hash' => '61VjPdR',
    'container.build_id' => 'e75bba48',
    'container.build_time' => 1645001129,
], __DIR__.\DIRECTORY_SEPARATOR.'Container61VjPdR');
