<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG5QTMEs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG5QTMEs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG5QTMEs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG5QTMEs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG5QTMEs\App_KernelDevDebugContainer([
    'container.build_hash' => 'G5QTMEs',
    'container.build_id' => '11abbc78',
    'container.build_time' => 1644221799,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG5QTMEs');
