<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZmclMel\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZmclMel/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZmclMel.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZmclMel\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZmclMel\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZmclMel',
    'container.build_id' => '6c9115c5',
    'container.build_time' => 1643618503,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZmclMel');
